# Operacje wektorowe i macierzowe
Algebra liniowa

In [1]:
import numpy

## Macierz identycznościowa
Dowolna macierz z dowolnej strony da tę sama macierz
$IA = AI = A$

In [2]:
numpy.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Trasnspozycja

$<x, Ay> = <A^Tx, y>$

In [3]:
A = numpy.array([[1, 2], [3, 4], [5, 6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
numpy.transpose(A)

array([[1, 3, 5],
       [2, 4, 6]])

## Macierz odwrotna
$A^{-1}A = AA^{-1} = I$

In [5]:
B = numpy.array([[1, 2], [3, 4]])
numpy.linalg.inv(B)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

$$Ax = y$$
$$x  = A^{-1}y$$
### RACZEJ TAK NIE ROBIMY (MINUSOWE PUNKTY)

## Norma wektora/macierzy
$||x||_2$, też inne
$$||x||_k = (\sum|x_i|^k)^\frac{1}{k}$$

In [6]:
X = numpy.array([1, 2, 3])
numpy.linalg.norm(X)

3.7416573867739413

$A$ - macierz
$$||A|| := sup(||Ax||) = sup(\frac{||Ax||}{||x||})$$ 
(zależnie czy ||x|| jest czy nie jest 0)
$$||Ax|| \leq ||A|| \cdot ||x||$$

## Iloczyn wektorowy

#### Nie tak, to jest po elementach: 

In [7]:
A = numpy.array([[1, 2], [3, 4]])
B = numpy.array([[9, 8], [7, 6]])

In [8]:
A * B

array([[ 9, 16],
       [21, 24]])

#### Tak:

In [9]:

A.dot(B)

array([[23, 20],
       [55, 48]])

In [10]:
A@B

array([[23, 20],
       [55, 48]])

In [11]:
numpy.dot(A, B)

array([[23, 20],
       [55, 48]])

In [12]:
X = numpy.array([1, 2, 3])
Y = numpy.array([5, 6, 7])
X@Y

38

In [13]:
X.transpose()@Y

38

In [14]:
X.dot(Y)

38

In [15]:
X@Y.transpose()

38

$$<x, y> = ||x||_2 \cdot ||y||_2 \cdot \cos{kąt(x, y)}$$

## Zmiana kształtu macierzy

In [16]:
A = numpy.array([1, 2, 3, 4, 5, 6])
A = A.reshape((2, 3))
A

array([[1, 2, 3],
       [4, 5, 6]])

### Ułożenie elementów w wektor

In [17]:
A.flatten()

array([1, 2, 3, 4, 5, 6])

## Operacja po elementach
for i in x - tak jakby lista list

## Macierz o zadanej diagonalnej

In [18]:
v = [1, 2, 3, 4]
numpy.diag(v)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [19]:
A = numpy.array([[1, 2], [3, 4]])
print(A)
numpy.diag(A)

[[1 2]
 [3 4]]


array([1, 4])

In [20]:
numpy.arange(1, 6)
# range ale numpy.array

array([1, 2, 3, 4, 5])

# Układy równań liniowych

$$\left\{ \begin{array}{rl}
a_{11}x_1 + ... + a_{1n}x_n = b_1 \\
a_{21}x_1 + ... + a_{2n}x_n = b_2 \\
...\\
a_{n1}x_1 + ... + a_{nn}x_n = b_n
\end{array} \right.$$

$$Ax=b$$

Na razie tylko macierze kwadratowe

Równania liniowe da się rozwiązać, kwadratowe i wyżej nie zawsze

## Układy łatwe do rozwiązania

### Układ z macierzą diagonalną

In [21]:
# x = b = [] 
# for i in range(1, n):
#     x[i] = b[i]/A[i][i]

### Układ z macierzą dolnotrójkątną

for i in [1, ... n]: 
    $x_i = (b_i - \sum^{n-1}_{j=1}n_{ij}x_j)/a_{ij}$

### Układ z macierzą górnotrójkątną

for i in [1, ... n]: $x_i = (b_i - \sum^n_{j=i+1}a_{ij}x_j)/a_{ij}$

## Rozkład LU / Eliminacja Gaussa

Załóżmy: A - nieosobliwa, kwadratowa macierz 

Znaleźliśmy: L - dolnotrójkątna, U - górnotrójkątna
$$ A = L \cdot U$$

Rozwiązanie 
$$Ax = b$$
$$LUx = b$$

$$y = Ux$$


#### 1. Rozwiązujemy 
$$L \cdot y = b$$
$0(n^2)$

#### 2. Rozwiązujemy 
$$ Ux = y$$
$0(n^2)$

### Jak otrzymać $L$ i $U$?
Koszt rozkładu: $0(n^3)$