In [2]:
import numpy as np

# Zadanie 9.1. 
Stosując funkcję `numpy.linalg.eig` z Octave, określ wektory własne i wartości
własne następujących macierzy:


In [3]:
M1 = np.array([
    [4.5, 3, 3.5],
    [-1,1,-1],
    [-0.5,-1,0.5]
])
M2 = np.array([
    [5998.5, 5997, 5997.5],
    [-2998,-2996,-2998],
    [0.5,1,0.5]
])
M3 = np.array([
    [6.5, 7, 9.5],
    [-1,1,-1],
    [-2.5,-5,-5.5]
])
M4 = np.array([
    [6.5, 3, 1.5],
    [-3,-1,-3],
    [1.5,3,6.5]
])
M5 = np.array([
    [2,-2,0],
    [2,2,0],
    [0,1,1]
])
M6 = np.array([
    [1,-1],
    [-1,1]
])
M7 = np.array([
    [1,-1],
    [1,-1]
])

In [4]:
def print_wektory_wlasnosci_wlasne(M):
    eig = np.linalg.eig(M)
    print(f"Macierz: \n {M} \n Własnosci wlasne: {eig[0]} \n Wektory wlasne: {eig[1]}\n\n")
np.linalg.eig(M2)

(array([3.00000000e+03, 2.82287566e+00, 1.77124344e-01]),
 array([[-8.94427191e-01, -7.57219144e-01, -7.87135075e-01],
        [ 4.47213595e-01,  6.43155402e-01,  2.05841622e-01],
        [-6.12077129e-20,  1.13887211e-01,  5.81418610e-01]]))

In [5]:
print_wektory_wlasnosci_wlasne(M1)
print_wektory_wlasnosci_wlasne(M2)
print_wektory_wlasnosci_wlasne(M3)
print_wektory_wlasnosci_wlasne(M4)
print_wektory_wlasnosci_wlasne(M5)
print_wektory_wlasnosci_wlasne(M6)
print_wektory_wlasnosci_wlasne(M7)

Macierz: 
 [[ 4.5  3.   3.5]
 [-1.   1.  -1. ]
 [-0.5 -1.   0.5]] 
 Własnosci wlasne: [3. 1. 2.] 
 Wektory wlasne: [[ 8.94427191e-01  7.07106781e-01  4.08248290e-01]
 [-4.47213595e-01  3.53883589e-16 -8.16496581e-01]
 [ 7.02166694e-17 -7.07106781e-01  4.08248290e-01]]


Macierz: 
 [[ 5.9985e+03  5.9970e+03  5.9975e+03]
 [-2.9980e+03 -2.9960e+03 -2.9980e+03]
 [ 5.0000e-01  1.0000e+00  5.0000e-01]] 
 Własnosci wlasne: [3.00000000e+03 2.82287566e+00 1.77124344e-01] 
 Wektory wlasne: [[-8.94427191e-01 -7.57219144e-01 -7.87135075e-01]
 [ 4.47213595e-01  6.43155402e-01  2.05841622e-01]
 [-6.12077129e-20  1.13887211e-01  5.81418610e-01]]


Macierz: 
 [[ 6.5  7.   9.5]
 [-1.   1.  -1. ]
 [-2.5 -5.  -5.5]] 
 Własnosci wlasne: [-3.  3.  2.] 
 Wektory wlasne: [[ 7.07106781e-01  8.94427191e-01 -4.08248290e-01]
 [ 8.40256684e-17 -4.47213595e-01  8.16496581e-01]
 [-7.07106781e-01 -1.21618839e-16 -4.08248290e-01]]


Macierz: 
 [[ 6.5  3.   1.5]
 [-3.  -1.  -3. ]
 [ 1.5  3.   6.5]] 
 Własnosci wlasne:

# Zadanie 9.2. 
Zaprogramuj procedurę implementującą metodę potęgową
$$ y_{k+1} = Ax_k$$
$$x_{k+1} = \frac{y_{k+1}}{||y_{k+1}||_2}$$
Należy przyjąć macierz, niezerowy wektor początkowy $x_0$ (przekazany jako parametr procedury)
oraz ilość iteracji.
Funkcja powinna zwracać przybliżenie wartości własnej oraz wektora własnego. Po znalezieniu przybliżenia wektora własnego $x_k$ należy przybliżyć wartość własną ilorazem Rayleigha
$$ \lambda_1 \approx \frac{x_k^TAx_k}{x_k^Tx_k}$$
Za kryterium stopu przyjmij ilości iteracji. Przetestuj ją dla macierzy mających dominującą
wartość własną. Porównaj wyniki z rezultatami funkcji `numpy.linalg.eig`.

In [6]:
def print_wyniki_funkcji(M, f, x_0):
    try:
        w = f(M, x_0, 100)
        print(f"Macierz: \n {M} \n Własnosci wlasne: {w[0]} \n Wektory wlasne: {w[1]}\n\n")
    except Exception:
        print(f"Macierz \n{M} \n BŁĄÐ")

In [7]:
def metoda_potegowa(A: np.array, x_0: np.array, iterations: int):
    x = [x_0]
    y = []
    lambdy = []
    for k in range(iterations):
        y.append(A@x[-1])
        x.append(y[-1]/np.linalg.norm(y[-1]))
        lambdy.append((np.transpose(x[-1])@A@x[-1])/(np.transpose(x[-1])@x[-1]))
    return lambdy[-1], x[-1]

In [8]:
print_wyniki_funkcji(M1, metoda_potegowa, [1, 1, 1])
print_wyniki_funkcji(M2, metoda_potegowa, [1, 1, 1])
print_wyniki_funkcji(M3, metoda_potegowa, [1, 1, 1])
print_wyniki_funkcji(M4, metoda_potegowa, [1, 1, 1])
print_wyniki_funkcji(M5, metoda_potegowa, [1, 1, 1])
print_wyniki_funkcji(M6, metoda_potegowa, [1, 2])
print_wyniki_funkcji(M7, metoda_potegowa, [1, 1])

Macierz: 
 [[ 4.5  3.   3.5]
 [-1.   1.  -1. ]
 [-0.5 -1.   0.5]] 
 Własnosci wlasne: 2.9999999999999996 
 Wektory wlasne: [ 8.94427191e-01 -4.47213595e-01 -4.44089210e-17]


Macierz: 
 [[ 5.9985e+03  5.9970e+03  5.9975e+03]
 [-2.9980e+03 -2.9960e+03 -2.9980e+03]
 [ 5.0000e-01  1.0000e+00  5.0000e-01]] 
 Własnosci wlasne: 3000.0 
 Wektory wlasne: [ 8.94427191e-01 -4.47213595e-01  1.84975487e-20]


Macierz: 
 [[ 6.5  7.   9.5]
 [-1.   1.  -1. ]
 [-2.5 -5.  -5.5]] 
 Własnosci wlasne: 3.0 
 Wektory wlasne: [ 0.57735027 -0.57735027  0.57735027]


Macierz: 
 [[ 6.5  3.   1.5]
 [-3.  -1.  -3. ]
 [ 1.5  3.   6.5]] 
 Własnosci wlasne: 4.999999999999999 
 Wektory wlasne: [ 0.57735027 -0.57735027  0.57735027]


Macierz: 
 [[ 2 -2  0]
 [ 2  2  0]
 [ 0  1  1]] 
 Własnosci wlasne: 1.8823529411764706 
 Wektory wlasne: [-0.70014004 -0.70014004  0.14002801]


Macierz: 
 [[ 1 -1]
 [-1  1]] 
 Własnosci wlasne: 2.0 
 Wektory wlasne: [-0.70710678  0.70710678]


Macierz: 
 [[ 1 -1]
 [ 1 -1]] 
 Własnosci wl

/tmp/ipykernel_19867/3898860104.py:7: RuntimeWarning: invalid value encountered in divide
  x.append(y[-1]/np.linalg.norm(y[-1]))


In [9]:
metoda_potegowa(M6, [1, 2], 100)

(2.0, array([-0.70710678,  0.70710678]))

In [10]:
print(M1)
print(metoda_potegowa(M1, np.array([1, 1, 1]), 100))

[[ 4.5  3.   3.5]
 [-1.   1.  -1. ]
 [-0.5 -1.   0.5]]
(2.9999999999999996, array([ 8.94427191e-01, -4.47213595e-01, -4.44089210e-17]))


# Zadanie 9.3
Przypuśćmy, że została zaimplementowana uproszczona metoda potęgowa, w której nie ma normowania, tzn.
$$ x_{k+1} = Ax_k$$
Jaka jest różnica? W jakim przypadku zadziała ona gorzej niż pełna metoda?

In [11]:
def uproszczona_metoda_potegowa(A: np.array, x_0: np.array, iterations: int):
    x = [x_0]
    lambdy = []
    for _ in range(iterations):
        x.append(A@x[-1])
        lambdy.append((np.transpose(x[-1])@A@x[-1])/(np.transpose(x[-1])@x[-1]))
    return lambdy[-1], x[-1]

In [12]:
def print_wyniki_funkcji(M, f, x_0):
    try:
        w = f(M, x_0, 100)
        print(f"Macierz: \n {M} \n Własnosci wlasne: {w[0]} \n Wektory wlasne: {w[1]}\n\n")
    except Exception:
        print(f"Macierz \n{M} \n BŁĄÐ")

In [16]:
print_wyniki_funkcji(M1, uproszczona_metoda_potegowa, [1, 1, 1])
print_wyniki_funkcji(M2, uproszczona_metoda_potegowa, [1, 1, 1])
print_wyniki_funkcji(M3, uproszczona_metoda_potegowa, [1, 1, 1])
print_wyniki_funkcji(M4, uproszczona_metoda_potegowa, [1, 1, 1])
print_wyniki_funkcji(M5, uproszczona_metoda_potegowa, [1, 1, 1])
print_wyniki_funkcji(M6, uproszczona_metoda_potegowa, [1, 2])
print_wyniki_funkcji(M7, uproszczona_metoda_potegowa, [1, 1])

Macierz: 
 [[ 4.5  3.   3.5]
 [-1.   1.  -1. ]
 [-0.5 -1.   0.5]] 
 Własnosci wlasne: 2.9999999999999996 
 Wektory wlasne: [ 3.09226512e+48 -1.54613256e+48  1.85485856e+32]


Macierz: 
 [[ 5.9985e+03  5.9970e+03  5.9975e+03]
 [-2.9980e+03 -2.9960e+03 -2.9980e+03]
 [ 5.0000e-01  1.0000e+00  5.0000e-01]] 
 Własnosci wlasne: nan 
 Wektory wlasne: [nan nan nan]


Macierz: 
 [[ 6.5  7.   9.5]
 [-1.   1.  -1. ]
 [-2.5 -5.  -5.5]] 
 Własnosci wlasne: 3.0000000000000173 
 Wektory wlasne: [ 1.54613256e+48 -1.54613256e+48  1.54613256e+48]


Macierz: 
 [[ 6.5  3.   1.5]
 [-3.  -1.  -3. ]
 [ 1.5  3.   6.5]] 
 Własnosci wlasne: 5.0 
 Wektory wlasne: [ 2.36658272e+70 -2.36658272e+70  2.36658272e+70]


Macierz: 
 [[ 2 -2  0]
 [ 2  2  0]
 [ 0  1  1]] 
 Własnosci wlasne: 1.0 
 Wektory wlasne: [                   0                    0 -3689348814741910322]


Macierz: 
 [[ 1 -1]
 [-1  1]] 
 Własnosci wlasne: nan 
 Wektory wlasne: [0 0]


Macierz: 
 [[ 1 -1]
 [ 1 -1]] 
 Własnosci wlasne: nan 
 Wektory wl

/tmp/ipykernel_19867/3086365077.py:6: RuntimeWarning: overflow encountered in matmul
  lambdy.append((np.transpose(x[-1])@A@x[-1])/(np.transpose(x[-1])@x[-1]))
/tmp/ipykernel_19867/3086365077.py:6: RuntimeWarning: invalid value encountered in matmul
  lambdy.append((np.transpose(x[-1])@A@x[-1])/(np.transpose(x[-1])@x[-1]))
/tmp/ipykernel_19867/3086365077.py:5: RuntimeWarning: overflow encountered in matmul
  x.append(A@x[-1])
/tmp/ipykernel_19867/3086365077.py:5: RuntimeWarning: invalid value encountered in matmul
  x.append(A@x[-1])
/tmp/ipykernel_19867/3086365077.py:6: RuntimeWarning: invalid value encountered in scalar divide
  lambdy.append((np.transpose(x[-1])@A@x[-1])/(np.transpose(x[-1])@x[-1]))


# Zadanie 9.4
Wartości własne możemy próbować przybliżać prościej niż ilorazem Rayleigha.
Spróbuj użyć następujących przybliżeń:
- $\lambda_1 = \frac{(Ax_k)_3}{(x_k)_3}$
- $\lambda_1 = \frac{\sum^n_{i=1}(Ax_k)_i}{\sum^n_{i=1}(x_k)_i}\\$
Zmodyfikuj swoją procedurę tak, aby zwracała przybliżenia obliczane także tymi wzorami. Określ, czy te przybliżenia dają wyniki gorsze niż iloraz Rayleigha i jakie są ich słabości.

In [17]:
def zad94(A: np.array, x_0: np.array, iter: int):
    x = [x_0]
    y = []
    for _ in range(iter):
        y.append(A@x[-1])
        x.append(y[-1]/np.linalg.norm(y[-1]))
    return (A@x[-1])[2]/x[-1][2], sum(A@x[-1])/sum(x[-1])
zad94(M1, [1, 1, 1], 100)

(2.999999999570182, 3.000000000000001)

In [26]:
wypisz_i_porownaj = lambda M, x_0 : print(f"Macierz: \n{M} \n Wyniki z zad 9.4 {zad94(M, x_0, 100)} \n Wynik z oryginalnej metody potegowej: {metoda_potegowa(M, x_0, 100)[0]}\n")
wypisz_i_porownaj(M1, [1, 1, 1])
wypisz_i_porownaj(M2, [1, 1, 1])
wypisz_i_porownaj(M3, [1, 1, 1])
wypisz_i_porownaj(M4, [1, 1, 1])
wypisz_i_porownaj(M5, [1, 1, 1])
# wypisz_i_porownaj(M6, [1, 2])
# wypisz_i_porownaj(M7, [1, 1, 1])

Macierz: 
[[ 4.5  3.   3.5]
 [-1.   1.  -1. ]
 [-0.5 -1.   0.5]] 
 Wyniki z zad 9.4 (2.999999999570182, 3.000000000000001) 
 Wynik z oryginalnej metody potegowej: 2.9999999999999996

Macierz: 
[[ 5.9985e+03  5.9970e+03  5.9975e+03]
 [-2.9980e+03 -2.9960e+03 -2.9980e+03]
 [ 5.0000e-01  1.0000e+00  5.0000e-01]] 
 Wyniki z zad 9.4 (-3000.5004168195073, 2999.999999999999) 
 Wynik z oryginalnej metody potegowej: 3000.0

Macierz: 
[[ 6.5  7.   9.5]
 [-1.   1.  -1. ]
 [-2.5 -5.  -5.5]] 
 Wyniki z zad 9.4 (-3.0000000000000013, 3.0) 
 Wynik z oryginalnej metody potegowej: 3.0

Macierz: 
[[ 6.5  3.   1.5]
 [-3.  -1.  -3. ]
 [ 1.5  3.   6.5]] 
 Wyniki z zad 9.4 (5.0, 5.0) 
 Wynik z oryginalnej metody potegowej: 4.999999999999999

Macierz: 
[[ 2 -2  0]
 [ 2  2  0]
 [ 0  1  1]] 
 Wyniki z zad 9.4 (-4.0, 2.6666666666666665) 
 Wynik z oryginalnej metody potegowej: 1.8823529411764706



# Zadanie 9.5
Sprawdź, jak metoda potęgowa działa w następujących przypadkach: $\\$
a) $\lambda_1 = -\lambda_2 > |\lambda_3| \geq ... \geq |\lambda_n|\\$
b) $\lambda_1 = \lambda_2 > |\lambda_3| \geq ... \geq |\lambda_n|\\$
c) Wartość $\lambda_1$ jest zespolona $\\$
d) Wektor $x_0$ jest wektorem własnym dla innej wartości własnej niż $\lambda_1$, ale jest spełnione $\lambda_1 > \lambda_2 \geq |\lambda_3| \geq ... \geq |\lambda_n|\\$

In [28]:
def metoda_potegowa_wiekszy_output(A: np.array, x_0: np.array, iterations: int):
    x = [x_0]
    y = []
    lambdy = []
    for k in range(iterations):
        y.append(A@x[-1])
        x.append(y[-1]/np.linalg.norm(y[-1]))
        lambdy.append((np.transpose(x[-1])@A@x[-1])/(np.transpose(x[-1])@x[-1]))
    return lambdy[-len(M):], x[-len(M)]

### a) 
$\lambda_1 = -\lambda_2 > |\lambda_3| \geq ... \geq |\lambda_n|\\$

In [33]:
M = M3
print(M)
print(np.linalg.eig(M))
print(metoda_potegowa_wiekszy_output(M, [1, 1, 1], 100))

[[ 6.5  7.   9.5]
 [-1.   1.  -1. ]
 [-2.5 -5.  -5.5]]
(array([-3.,  3.,  2.]), array([[ 7.07106781e-01,  8.94427191e-01, -4.08248290e-01],
       [ 8.40256684e-17, -4.47213595e-01,  8.16496581e-01],
       [-7.07106781e-01, -1.21618839e-16, -4.08248290e-01]]))
([3.000000000000001, 0.8181818181818177, 3.0], array([ 0.57735027, -0.57735027,  0.57735027]))


### b) 
$\lambda_1 = \lambda_2 > |\lambda_3| \geq ... \geq |\lambda_n|\\$

In [34]:
M = M4
print(M)
print(np.linalg.eig(M))
print(metoda_potegowa_wiekszy_output(M, [1, 1, 1], 100))

[[ 6.5  3.   1.5]
 [-3.  -1.  -3. ]
 [ 1.5  3.   6.5]]
(array([5., 2., 5.]), array([[ 0.80178373,  0.40824829, -0.812642  ],
       [-0.53452248, -0.81649658,  0.12132385],
       [ 0.26726124,  0.40824829,  0.5699943 ]]))
([4.999999999999999, 5.0, 4.999999999999999], array([ 0.57735027, -0.57735027,  0.57735027]))
